var a=10;
document.write("Result:<br>");
document.write("The value of a is:"+a+"<br>");
document.write("------------<br>");
document.write("<br>The value of ++a is:"+(++a)+"<br>");
document.write("Now the value of a is:"+a+"<br>");
document.write("<br>The value of a++ is:"+(a++)+"<br>");
document.write("Now the value of a is:"+a+"<br>");
document.write("<br>The value of --a is:"+(--a)+"<br>");
document.write("Now the value of a is:"+a+"<br>");
document.write("<br>The value of a-- is:"+(a--)+"<br>");
document.write("Now the value of a is:"+a+"<br>");